### PR TITLE
add nodejs builtins import group

### PR DESCRIPTION
**Pull request by bfmiv**
Resolves https://github.com/lydell/eslint-plugin-simple-import-sort/issues/20

### CODE REVIEW

**Comment by lydell** [comment]
Thanks! Code is the easy part. It’s not decided yet if #20 is going to be changed or not. So I’m going to close this for now. Hope that’s OK!

(Btw, `validate-npm-package-name` already knows and tells us which packages are builtin, so there’s no need for a new dependency.)

**Comment by bfmiv** [comment]
Hey, no problem - its your library! I just needed this functionality and figured I'd open a PR to share.

Do you have an ETA for a decision on #20? A node builtins group is fairly critical for us. I had planned on using this in place of [import/order](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md), but I would prefer not to maintain a separate fork long term.

Thank you for the quick response.

**Comment by lydell** [comment]
I'm sorry, there’s no ETA. Since this plugin isn’t very popular, it’s hard to gauge how popular feature requests are. All I know is that a few people want Node.js core modules separately, and a few don’t. What all silent users want is unknown.

I used to sort Node.js core modules separately, but then stopped when I started using some sorting plugin that didn’t do so. I was amazed at how quickly I got used to it, so I didn’t do it when writing this plugin either. Today I don’t think it’s helpful to me anymore to do that separation. But it wouldn’t hurt me either.

Could you expand on why “node builtins group is fairly critical” for you?

**Comment by namnm** [comment]
> why “node builtins group is fairly critical”
For me the first reason is like, I would know which modules are needed to be installed or downloaded. Built-in ones are not.

**Comment by lydell** [comment]
@namnm Thanks for the input! In what situations do you look at imports in files to know which modules need to be installed?

**Comment by bfmiv** [comment]
Maybe "critical" isn't the right word - combining native and third party imports certainly isn't going to break any builds.

From a readability perspective, maintaining parity with other standard formatting tools (such as eslint's [import/order](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md) and [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports)) is a key factor in choosing a plugin.

**Comment by NexZhu** [comment]
Node now support inporting builtin modules with `node:path`, `node:fs`, etc., can we support options to sort imports from `node:*` before npm modules?

**Comment by lydell** [comment]
@NexZhu Hmm, yes, that probably makes sense to have as the default! Can you open an issue?

**Comment by NexZhu** [comment]
> @NexZhu Hmm, yes, that probably makes sense to have as the default! Can you open an issue?

https://github.com/lydell/eslint-plugin-simple-import-sort/issues/109

**Pull request closed without merging**
