### PR TITLE
Add recommended preset

### PR DESCRIPTION
**Pull request by remcohaszing**
The readme has been changed to recommend the use of presets.

### CODE REVIEW

**Comment by lydell** [comment]
Thanks for your pull request!

The eslint-plugin-import rules in the example configuration are there to show that eslint-plugin-import can do stuff that eslint-plugin-simple-import-sort doesn't, but is kind of related to formatting of sorted imports. So I don't think we should use `plugin:import/recommended`.

IMO, the `plugin:prettier/recommended` config is very confusing. I think recommended configs make sense for plugins with lots of rules to help people get going. But for small, maybe even single-rule, plugins I think recommended configs just makes things less clear.

**Comment by remcohaszing** [comment]
Alright, I’ll revert the recommendation of using `plugin:import/recommended` and `plugin:prettier/recommended`.

Just an FYI: `plugin:prettier/recommended` includes `eslint-config-prettier`. This also turns off plugins that might conflict with prettier.

Are you interested in the addition of the recommended preset for this plugin?

**Comment by lydell** [comment]
> Just an FYI: plugin:prettier/recommended includes eslint-config-prettier. This also turns off plugins that might conflict with prettier.

I know, I’m the author of eslint-plugin-prettier and a user of eslint-plugin-prettier ;)

> Are you interested in the addition of the recommended preset for this plugin?

I don’t think I’m convinced.

**Comment by remcohaszing** [comment]
Alright I’ll close the PR then. It was a minor addition anyway.

**Pull request closed without merging**
